<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RELATED_IDEAS_TAB</name>
   <tag></tag>
   <elementGuidId>897fdc90-1c06-469e-80e0-40705d6e6713</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='tab-content']//a[text()='ideas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tab-content']//a[text()='ideas']</value>
   </webElementProperties>
</WebElementEntity>
