<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>New Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a835b014-3693-41ae-a969-3933fe95f1be</testSuiteGuid>
   <testCaseLink>
      <guid>35d27b2a-41d6-498d-94ff-863d44f23080</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TEMPLATES/LOGIN/LOGIN_TEMPLATE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc28f7bc-7857-4109-ad7f-67ca436317af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36064dd4-1f6d-4cb4-8ffe-50539143803e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>779c3ad8-0ce8-4da9-9e11-471d925b379f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c62b78eb-eb10-496b-b9c3-a670d62e92ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TEMPLATES/IDEATION/IDEA/IDEA_ADD_RELATED_TOPICS_TEMPLATE</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e7959e46-60d3-4fa8-b881-e6a19c47c6cc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/IDEATION/IDEA</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e7959e46-60d3-4fa8-b881-e6a19c47c6cc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IDEA_TITLE</value>
         <variableId>6645f1f0-38d0-4dcb-aa3b-a902c4bfb3e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00585ffb-1f6e-4f63-b39b-71bdb7779536</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7b1046d-1d53-4f55-8075-688d34a6687d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b28406db-eef6-437c-8868-ab37e21ad714</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53ced51a-c3ab-4dc3-8e7a-25bb4e5ae1db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e673a14-fb4f-4d2a-b9e8-270ff791fb8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a01b7b5c-6b3e-4d68-ae52-6a101acfe53c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01330a04-9c3c-45a4-aed6-cfe67ad290c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a717953c-628a-4832-87a5-7a3fa81ad026</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9506643f-f34e-429a-a5ee-c3d1f644617e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
