<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OC_RISK_RELATED_STATUS_FIELD</name>
   <tag></tag>
   <elementGuidId>559a31ad-c0f8-4a06-948a-9dd762522f57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//app-related-risks//*[contains(@class,'card-status')]/span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//app-related-risks//*[contains(@class,'card-status')]/span)[1]</value>
   </webElementProperties>
</WebElementEntity>
