<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RELATED_RISKS_TAB</name>
   <tag></tag>
   <elementGuidId>9005eabc-80c4-41ff-9224-3ffa4f2f53f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='tab-content']//a[text()='risks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tab-content']//a[text()='risks']</value>
   </webElementProperties>
</WebElementEntity>
