<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NOTIFICATION_LIST</name>
   <tag></tag>
   <elementGuidId>e56281ae-db6c-42a7-800a-8fb69993bcf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ngb-popover-window</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ngb-popover-window</value>
   </webElementProperties>
</WebElementEntity>
