<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LV_IMPORTANCE_FIELD</name>
   <tag></tag>
   <elementGuidId>9effd150-f38e-41ff-8b42-872d9788fb5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[contains(@class,'card-stage')]//span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[contains(@class,'card-stage')]//span)[1]</value>
   </webElementProperties>
</WebElementEntity>
