<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OC_SOURCE_TYPE_BUTTON</name>
   <tag></tag>
   <elementGuidId>50fb6d64-7912-4e22-9774-bd594bb50340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='dropdownBasic1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='dropdownBasic1']</value>
   </webElementProperties>
</WebElementEntity>
