<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OC_CLOSE_BUTTON</name>
   <tag></tag>
   <elementGuidId>3790ed0b-bdcf-4bed-9180-f2b167a612ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@ngbtooltip='close']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@ngbtooltip='close']/i</value>
   </webElementProperties>
</WebElementEntity>
