<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OC_MEMBERS_BUTTON</name>
   <tag></tag>
   <elementGuidId>ccd3f191-28ab-4340-a455-35e29f4c05e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@ngbtooltip='members']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@ngbtooltip='members']/i</value>
   </webElementProperties>
</WebElementEntity>
