<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OC_REVIEW_COMMENT_TEXTAREA</name>
   <tag></tag>
   <elementGuidId>3b50bdb0-afcb-4a97-947e-81093c02653d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[contains(@placeholder,'optional')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@placeholder,'optional')]</value>
   </webElementProperties>
</WebElementEntity>
