<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OC_SUMMARY_PARAGRAPH</name>
   <tag></tag>
   <elementGuidId>56449ab8-1555-45f6-83ae-317b990c580c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//markdown/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//markdown/p</value>
   </webElementProperties>
</WebElementEntity>
